language: python
python:
- 3.8.2
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: AFbvaFoS2UoKAgAKdKcVSiIOiiDAgTMrNKsg/qh5JvdLWtpNmRk1J+RDW1eIBU618PqHJvdkiiiv8sx8h3dleUmy5l8eIy24opHNq5KM7oR/c99R8IWvrK++7iD6v1JMxeDfNC/qzy/1kgM7RhXUVyU2HZhlOVGh5JVYDf8IgbM744LTOfQ+UahhUxTjLjYKDntPs2ki4G86uh0AR4EaPTIK9XyD2euXBhzbDFl2c3hkoODJ01z5Icfiw92QXAQo7+ppm4claTAp4tZ+ruK7mdD4czWvZ7V5qnd2+qgQRT2UZbJELEOZYJay2C4mlSFWibwSLTOUu0BmsVnNHZqOq/feteyAYVh3BpKk3E5SErJsCnffyIWwijBK4b4MzvXp5ZoWjZWTYQ31NImlEAJcYiZfNkzZEVZF+KUsYqpHSprR1y86/FpTDiJpPiYlCEsO6e0nIluo7Hm0EAMh32jTw4QbOXcPEAwe6ZKOlJ6TquyFe3nyVdu9OUIrxFtjx2JeT35fSYfl3EYersgl2/saq68+6PGNzOkAMgMsjKBl0bL/ojRD0akWqJTbfmkv65xFQY/y/cvH75+IQ4yxpjmSbsUkxmQimf0xMFCidnZheaHJSQYMdCLe4PxQdaoRdWuFV0TrCXziAZSKx1ppPpS5CSK3IteKn88KsKr1xSrQeQo=
  app: hero-test-lf
  on:
    repo: souluanf/hero_test
    all_branches: true
